# Generated by Django 4.1.2 on 2022-10-22 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_phone', models.CharField(max_length=255)),
                ('receiver_phone', models.CharField(max_length=255)),
                ('time_started', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('Successful', 'Successful'), ('Failed', 'Failed')], default='Not Started', max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('Execute', 'Execute'), ('Timer', 'Timer'), ('Web-Hook', 'Web Hook')], default='Execute', max_length=255)),
                ('call', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.call')),
            ],
        ),
    ]
