# Generated by Django 4.1.2 on 2022-10-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='message_file',
            field=models.FileField(blank=True, null=True, upload_to='audios'),
        ),
    ]
