# Generated by Django 4.1.2 on 2022-10-22 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_trigger_message_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='call',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.call'),
        ),
    ]
