# Generated by Django 4.1.2 on 2022-10-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voipconfig',
            name='internal_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
